# Generated by Django 4.2.29 on 2026-04-13 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('disbursed', 'Disbursed')], default='disbursed', max_length=10)),
                ('disbursed_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_ref', models.CharField(max_length=100, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('disbursed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_disbursements', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursements', to='billing.invoice')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Disbursement',
                'verbose_name_plural': 'Payment Disbursements',
                'ordering': ['-disbursed_at'],
                'unique_together': {('invoice', 'staff')},
            },
        ),
    ]
