# Generated by Django 4.2.29 on 2026-06-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_paymentdisbursement'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='company_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
