# Generated by Django 6.0.3 on 2026-03-29 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('move_size', models.CharField(choices=[('studio', 'Studio'), ('one_bedroom', '1 Bedroom'), ('two_bedroom', '2 Bedroom'), ('three_bedroom', '3 Bedroom'), ('office_small', 'Small Office'), ('office_large', 'Large Office')], max_length=20)),
                ('pickup_address', models.TextField()),
                ('dropoff_address', models.TextField()),
                ('estimated_distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_staff_count', models.PositiveSmallIntegerField(default=10)),
                ('requested_truck_count', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-scheduled_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('supervisor', 'Supervisor'), ('mover', 'Mover')], default='mover', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_assignments', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='jobs.job')),
                ('staff', models.ForeignKey(limit_choices_to={'role': 'mover-staff'}, on_delete=django.db.models.deletion.PROTECT, related_name='job_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Assignment',
                'verbose_name_plural': 'Job Assignments',
                'unique_together': {('job', 'staff')},
            },
        ),
        migrations.CreateModel(
            name='JobTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='truck_assignments', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_trucks', to='jobs.job')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_trucks', to='fleet.truck')),
            ],
            options={
                'verbose_name': 'Job Truck',
                'verbose_name_plural': 'Job Trucks',
                'unique_together': {('job', 'truck')},
            },
        ),
    ]
