# Generated by Django 4.2.29 on 2026-06-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_application_deadline_job_attendance_pin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtruck',
            name='allocation_method',
            field=models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], default='manual', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='move_size',
            field=models.CharField(choices=[('studio', 'Studio'), ('one_bedroom', '1 Bedroom'), ('two_bedroom', '2 Bedroom'), ('three_bedroom', '3 Bedroom'), ('four_bedroom', '4 Bedroom'), ('five_bedroom', '5 Bedroom'), ('six_bedroom', '6 Bedroom'), ('office_small', 'Small Office'), ('office_large', 'Large Office')], max_length=20),
        ),
    ]
