# Generated by Django 6.0.3 on 2026-03-29 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('truck_type', models.CharField(choices=[('small', 'Small (1-ton)'), ('medium', 'Medium (3-ton)'), ('large', 'Large (7-ton)'), ('extra_large', 'Extra Large (10-ton)')], max_length=20)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
                ('color', models.CharField(blank=True, max_length=50)),
                ('capacity_tons', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_job', 'On Job'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('mileage_km', models.PositiveIntegerField(default=0)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trucks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Truck',
                'verbose_name_plural': 'Trucks',
                'ordering': ['plate_number'],
            },
        ),
    ]
