# Generated by Django 6.0.3 on 2026-03-29 05:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('punctuality', 'Punctuality'), ('teamwork', 'Teamwork'), ('care_of_goods', 'Care of Goods'), ('physical_fitness', 'Physical Fitness'), ('communication', 'Communication'), ('overall', 'Overall')], default='overall', max_length=20)),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 (very poor) to 5 (excellent).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='jobs.job')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Review',
                'verbose_name_plural': 'Staff Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('job', 'reviewee', 'category')},
            },
        ),
    ]
